---
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: portunus
    name: portunus
  spec:
    replicas: 1
    selector:
      app: portunus
      deploymentconfig: portunus
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: portunus
          deploymentconfig: portunus
      spec:
        containers:
          - image: <IMAGE NAME>
            imagePullPolicy: Always
            name: portunus
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
      - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    name: portunus      
  spec:
    selector:                  
      app: portunus
    ports:
    - name: portunus-webport
      port: 8080              
      protocol: TCP
      targetPort: 8080
#- apiVersion: route.openshift.io/v1
#  kind: Route
#  metadata: 
#    name: portunus
#    port:
#      targetPort: portunus-webport
#  to:
#    kind: Service
#    name: portunus
#    weight: 100
#  wildcardPolicy: None
        
